### PR TITLE
Glt 226

### PR DESCRIPTION
**Pull request by djcooke**
Scanner-related interfaces, merging into GLT-219 (Box classes and AJAX)

### CODE REVIEW

**Comment by djcooke** [comment]
retest

**Comment by djcooke** [comment]
Build for merge with GLT-219 fails due to GLT-219 no compiling on its own. Will retest once GLT-219 is compiling successfully again.

@apmasell all discussed changes have been implemented if you'd like to review them again

**Comment by apmasell** [comment]
Okay. Go for it.

**Comment by djcooke** [comment]
retest

**Comment by djcooke** [comment]
@apmasell Sorry, could you review the small change I just pushed?

**Comment by djcooke** [comment]
Updated the Javadoc to be a bit more specific about it.

A scanner (VisionMate at least) cannot auto-detect the box size, so it must be configured before the scan; otherwise, the scanner just tries to fit what it sees into the dimensions it was expecting.

If expected size is smaller than the scanned rack, some barcodes will be omitted. If the expected size is larger than actual size, then there will be extra empty positions reported, and the real barcode data will be scattered to unpredictable positions. In either scenario, some tubes won't be reported at all because they didn't line up with the grid defined by the expected size.

The gist of it is "set the expected box size, or unpredictable and undetectable (by the scanner) things will happen."

**Pull request merged**
