### PR TITLE
GLT-1088 change Library Dilution units to ng/ul

### PR DESCRIPTION
**Pull request by callunity**

### CODE REVIEW

**Comment by djcooke** [comment]
Are we sure this is OICR-specific? I think in EI's current production MISO, the units aren't accurately displayed everywhere, so while it was intended to be nM, that may not even be what they use

**Comment by callunity** [comment]
I'll check with Chris. I haven't heard that EI might want different units.

**Comment by callunity** [comment]
It sounds like EI does indeed want ng/ul for Dilutions. I'm closing this and PRing it into develop.

**Comment by callunity** [comment]
Reopening to PR into `oicr` while EI figures out how they want to make that conversion happen (how they want to convert the values already in their db).

**Comment by djcooke** [comment]
:+1:

**Comment by tonydebat** [comment]
👍

**Pull request merged**
