### PR TITLE
GLT-652 use OICR logo in header

### PR DESCRIPTION
**Pull request by callunity**
And official colours: http://imgur.com/LujCL0C

### CODE REVIEW

**Comment by apmasell** [comment]
:+1:

**Comment by djcooke** [comment]
:+1: Now we must change all the shades of blue to shades of green

**Comment by callunity** [comment]
@djcooke official colours: http://imgur.com/LujCL0C

**Comment by morgantaschuk** [comment]
That is horrifying.

## 

Morgan Taschuk
Senior Manager, Genome Sequence Informatics

Twitter: @morgantaschuk

**Comment by frankie13** [comment]
:+1: :100:

**Pull request merged**
